/**
 * Converts the SQLite dump in data/ into a Postgres seed file.
 *
 * The dump is nearly PG-compatible already; the parts that are not are the
 * integer flag columns (SQLite has no boolean). Rather than hand-editing 534
 * INSERTs, this parses each row and re-emits it with those columns cast to
 * true/false, so the transform is mechanical and countable.
 */
import { readFileSync, writeFileSync } from 'node:fs';

const SRC = new URL('../data/adaptive_athlete_schema_and_seed.sql', import.meta.url);
const OUT = new URL('../supabase/seed/01_content.sql', import.meta.url);

/** Columns that are 0/1 in SQLite and boolean in Postgres. */
const BOOL_COLUMNS = {
  exercises: ['postpartum_friendly'],
  workout_templates: ['postpartum_friendly', 'requires_running', 'requires_ski'],
  exercise_equipment: ['required'],
};

/** Column order per table, read from the dump's own CREATE TABLE statements. */
function parseSchema(sql) {
  const schema = {};
  for (const m of sql.matchAll(/CREATE TABLE (\w+)\(([\s\S]*?)\);/g)) {
    const [, table, body] = m;
    const cols = [];
    let depth = 0, cur = '';
    for (const ch of body) {
      if (ch === '(') depth++;
      if (ch === ')') depth--;
      if (ch === ',' && depth === 0) { cols.push(cur.trim()); cur = ''; continue; }
      cur += ch;
    }
    if (cur.trim()) cols.push(cur.trim());
    schema[table] = cols
      .filter(c => !/^(PRIMARY|UNIQUE|FOREIGN|CHECK)\b/i.test(c))
      .map(c => c.split(/\s+/)[0]);
  }
  return schema;
}

/** Split a VALUES(...) tuple into raw SQL literals, respecting '' escapes. */
function splitValues(body) {
  const out = [];
  let cur = '', inStr = false;
  for (let i = 0; i < body.length; i++) {
    const ch = body[i];
    if (inStr) {
      cur += ch;
      if (ch === "'") {
        if (body[i + 1] === "'") { cur += "'"; i++; }
        else inStr = false;
      }
      continue;
    }
    if (ch === "'") { inStr = true; cur += ch; continue; }
    if (ch === ',') { out.push(cur.trim()); cur = ''; continue; }
    cur += ch;
  }
  if (cur.trim()) out.push(cur.trim());
  return out;
}

const sql = readFileSync(SRC, 'utf8');
const schema = parseSchema(sql);

const rows = {};
let total = 0, converted = 0;

for (const m of sql.matchAll(/INSERT INTO "(\w+)" VALUES\(([\s\S]*?)\);\n/g)) {
  const [, table, body] = m;
  const values = splitValues(body);
  const cols = schema[table];
  if (!cols) throw new Error(`No schema for table ${table}`);
  if (cols.length !== values.length) {
    throw new Error(`${table}: ${cols.length} columns but ${values.length} values`);
  }
  const boolCols = BOOL_COLUMNS[table] ?? [];
  const mapped = values.map((v, i) => {
    if (boolCols.includes(cols[i])) {
      converted++;
      if (v === 'NULL') return 'NULL';
      return v.trim() === '1' ? 'true' : 'false';
    }
    return v;
  });
  (rows[table] ??= []).push(`  (${mapped.join(',')})`);
  total++;
}

// Insert order respects foreign keys: primitives first, then joins.
const ORDER = [
  'equipment', 'exercises', 'exercise_equipment', 'tags',
  'workout_templates', 'workout_variants', 'workout_blocks', 'block_exercises',
  'workout_tags', 'substitutions', 'progression_rules',
];

const missing = Object.keys(rows).filter(t => !ORDER.includes(t));
if (missing.length) throw new Error(`Table(s) not in insert order: ${missing.join(', ')}`);

let out = `-- Generated by scripts/convert-seed.mjs from data/adaptive_athlete_schema_and_seed.sql\n`;
out += `-- Do not edit by hand. Re-run: node scripts/convert-seed.mjs\n\n`;
out += `begin;\n\n`;
for (const table of ORDER) {
  if (!rows[table]) continue;
  out += `insert into content.${table} (${schema[table].join(', ')}) values\n`;
  out += rows[table].join(',\n');
  out += `\non conflict (${table === 'exercise_equipment' ? 'exercise_id, equipment_id'
    : table === 'workout_tags' ? 'workout_id, tag_id' : 'id'}) do nothing;\n\n`;
}
out += `commit;\n`;

writeFileSync(OUT, out);

console.log(`tables:            ${ORDER.filter(t => rows[t]).length}`);
console.log(`rows parsed:       ${total}`);
console.log(`booleans converted: ${converted}`);
for (const t of ORDER) if (rows[t]) console.log(`  ${t.padEnd(20)} ${rows[t].length}`);
